name: Build succeeds on PR

on: 
  pull_request:
    branches:
      - master
      - main

jobs:
  Continuous-Integration:
    name: Build the project
    runs-on: ubuntu-latest
    steps:
        # Checkout the repository
        - name: Checkout the Repository
          uses: actions/checkout@v3
        
        # Setup Node.js environment
        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: 20

        # Install dependencies
        - name: Install Dependencies
          run: npm install --legacy-peer-deps

        # Generate Prisma client
        - name: Generate Prisma Client
          run: cd packages/db && npx prisma generate && cd ../..

        # Build the project
        - name: Run Build
          run: npm run build